using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FZ4P.DriverIc.IC.CML.CM824.RegisterMaps
{
    public static class RegisterMap
    {
        public const uint PART_ID = 0x2; // uint16, read/write : Unique 16-bit part identifier, set by hardware to indicate the chip model
        public const uint FW_STATUS = 0x6; // uint16, read/write : Firmware operation status
            public const uint FW_STATUS_READY = 0x1; // Bitfield : Indicates the firmware is ready to receive commands
        public const uint DEVICE_RESET = 0xc; // uint16, read/write : Set to 1 to reset the device
        public const uint SYS_STATUS = 0x100; // uint16, read/write : Firmware download control and status flags
            public const uint SYS_STATUS_SYS_READY = 0x1; // Bitfield : Indicates chip is ready
            public const uint SYS_STATUS_BOOT_FROM_FLASH = 0x40; // Bitfield : Set to boot from flash
            public const uint SYS_STATUS_HW_CHECKSUM_FAIL = 0x80; // Bitfield : Indicates checksum is incorrect
            public const uint SYS_STATUS_FW_DOWNLOAD_FINISH = 0x100; // Bitfield : Set to run MCU after firmware download has finished
            public const uint SYS_STATUS_MCU_STOP = 0x800; // Bitfield : Set to force stop MCU
        public const uint IMAGE_CHECKSUM = 0x102; // uint16, read/write : Checksum of the firmware image to download
        public const uint SYS_UNLOCK = 0x108; // uint16, read/write : Unlock code to access i2c registers addressed from 0x2000 to 0x4000
        public const uint FW_CHIP_ID = 0x2000; // uint16, read-only : Set by firmware to indicate chip model
        public const uint FW_UID_L = 0x2002; // uint16, read-only : This is the least significant 2 bytes of the Firmware UID
        public const uint FW_UID_H = 0x2004; // uint16, read-only : This is the most significant 2 bytes of the Firmware UID
        public const uint FW_BUILD_CONFIG_ID = 0x2006; // uint16, read-only : Firmware build configuration identifier
        public const uint FW_VERSION_MAJOR = 0x2008; // uint16, read-only : Firmware major version number
        public const uint FW_VERSION_MINOR = 0x200a; // uint16, read-only : Firmware minor version number
        public const uint FW_VERSION_PATCH = 0x200c; // uint16, read-only : Firmware patch number
        public const uint FW_ACTUATOR_ID = 0x200e; // uint16, read-only : Firmware actuator identifier
        public const uint SMA_CONFIG_VERSION = 0x2014; // uint32, read-only : Configuration version identifier
        public const uint FW_BUILD_DATE = 0x2018; // uint32, read-only : Firmware build date in YYYYMMDD format (binary-coded decimal)
        public const uint FW_BUILD_TIME = 0x201c; // uint32, read-only : Firmware build time in 00HHMMSS format (binary-coded decimal, right-aligned)
        public const uint MP_CALIB_PARAMS_VALID = 0x2020; // uint16, read/write : Signals to load motion processing calibration from flash when saved
            public const uint MP_CALIB_PARAMS_VALID_NOT_SET = 0x0; // State
            public const uint MP_CALIB_PARAMS_VALID_OK = 0x1; // State
        public const uint SET_IMU = 0x2022; // uint16, read/write : Select IMU model
            public const uint SET_IMU_BMI270 = 0x7; // State : Select Bosch BMI270 IMU
            public const uint SET_IMU_SCS3301 = 0x10; // State
        public const uint MP_GYR_XGG = 0x2024; // float, read/write : Sets the gyro gain for compensating shake around actuator X axis
        public const uint MP_GYR_YGG = 0x2028; // float, read/write : Sets the gyro gain for compensating shake around actuator Y axis
        public const uint MP_AXIS_ALIGNMENT = 0x2030; // uint8, read/write : Align gyro axes with actuator axes
            public const uint MP_AXIS_ALIGNMENT_ROT_0_DEGREES = 0x0; // State : Gyro Orientation angle 0 degree
            public const uint MP_AXIS_ALIGNMENT_ROT_90_DEGREES = 0x1; // State : Gyro Orientation angle 90 degrees
            public const uint MP_AXIS_ALIGNMENT_ROT_180_DEGREES = 0x2; // State : Gyro Orientation angle 180 degrees
            public const uint MP_AXIS_ALIGNMENT_ROT_270_DEGREES = 0x3; // State : Gyro Orientation angle 270 degrees
            public const uint MP_AXIS_ALIGNMENT_ROT_0_DEGREES_BACK = 0x4; // State : Gyro Orientation angle 0 degree back
            public const uint MP_AXIS_ALIGNMENT_ROT_90_DEGREES_BACK = 0x5; // State : Gyro Orientation angle 90 degrees back
            public const uint MP_AXIS_ALIGNMENT_ROT_180_DEGREES_BACK = 0x6; // State : Gyro Orientation angle 180 degrees back
            public const uint MP_AXIS_ALIGNMENT_ROT_270_DEGREES_BACK = 0x7; // State : Gyro Orientation angle 270 degrees back
        public const uint MP_GYRO_BIAS_X = 0x2032; // int16, read/write : Calibrated gyro offset
        public const uint MP_GYRO_BIAS_Y = 0x2034; // int16, read/write : Calibrated gyro offset
        public const uint MP_GYRO_BIAS_Z = 0x2036; // int16, read/write : Calibrated gyro offset
        public const uint MP_PHASE_COMP_X0 = 0x2038; // int32 Q0.31, read/write : Phase adjustment for compensating shake around actuator X axis. 1st value is for low frequency setting, 2nd is for high frequency setting
        public const uint MP_PHASE_COMP_X1 = 0x203c; // int32 Q0.31, read/write : Phase adjustment for compensating shake around actuator X axis. 1st value is for low frequency setting, 2nd is for high frequency setting
        public const uint MP_PHASE_COMP_Y0 = 0x2040; // int32 Q0.31, read/write : Phase adjustment for compensating shake around actuator Y axis. 1st value is for low frequency setting, 2nd is for high frequency setting
        public const uint MP_PHASE_COMP_Y1 = 0x2044; // int32 Q0.31, read/write : Phase adjustment for compensating shake around actuator Y axis. 1st value is for low frequency setting, 2nd is for high frequency setting
        public const uint MP_GAIN_POL_X = 0x2050; // int16, read/write : Sets polarity of motion processing output signal. Set to +1 for nominal. Set to -1 to invert
        public const uint MP_GAIN_POL_Y = 0x2052; // int16, read/write : Sets polarity of motion processing output signal. Set to +1 for nominal. Set to -1 to invert
        public const uint MP_GAIN_POL_Z = 0x2054; // int16, read/write : Sets polarity of motion processing output signal. Set to +1 for nominal. Set to -1 to invert
        public const uint MP_ACC_OFFSET_X = 0x2056; // int16, read/write : Accelerometer offset, subtracted from acc raw X axis
        public const uint MP_ACC_OFFSET_Y = 0x2058; // int16, read/write : Accelerometer offset, subtracted from acc raw Y axis
        public const uint MP_ACC_OFFSET_Z = 0x205a; // int16, read/write : Accelerometer offset, subtracted from acc raw Z axis
        public const uint SPI_MODE = 0x205c; // uint16, read/write : Select 3 or 4 wire master SPI modes
            public const uint SPI_MODE_CONTROLLER_3_WIRE = 0x0; // State : SPI 3 wire controller (generates SCK)
            public const uint SPI_MODE_PERIPHERAL_3_WIRE = 0x2; // State : SPI 3 wire intercept mode
        public const uint GYRO_RANGE = 0x205e; // uint16, read/write : Gyro full scale range override. Only used if in SPI peripheral mode. Not to be used with ST gyros
            public const uint GYRO_RANGE_DEFAULT = 0x0; // State : Use gyro full scale range default value
            public const uint GYRO_RANGE_DPS_125 = 0x1; // State : Gyro range +-125 dps
            public const uint GYRO_RANGE_DPS_250 = 0x2; // State : Gyro range +-250 dps
            public const uint GYRO_RANGE_DPS_500 = 0x3; // State : Gyro range +-500 dps
            public const uint GYRO_RANGE_DPS_1000 = 0x4; // State : Gyro range +-1000 dps
            public const uint GYRO_RANGE_DPS_2000 = 0x5; // State : Gyro range +-2000 dps
        public const uint CAL_FW_UID = 0x2080; // uint32, read/write : Firmware UID used for calibration
        public const uint CAL_TEMPERATURE_OFFSET_VALID = 0x2084; // uint16, read/write : Set to indicate `cal_temperature_offset` calibration should be used
            public const uint CAL_TEMPERATURE_OFFSET_VALID_NOT_SET = 0x0; // State
            public const uint CAL_TEMPERATURE_OFFSET_VALID_OK = 0x1; // State
        public const uint CAL_TEMPERATURE_OFFSET = 0x2086; // int16, read/write
        public const uint CAL_RESISTANCE_VALID = 0x2088; // uint16, read/write : Set to indicate `cal_resistance` calibration should be used
            public const uint CAL_RESISTANCE_VALID_NOT_SET = 0x0; // State
            public const uint CAL_RESISTANCE_VALID_OK = 0x1; // State
        public const uint CAL_RESISTANCE0 = 0x208c; // uint16, read/write
        public const uint CAL_RESISTANCE1 = 0x208e; // uint16, read/write
        public const uint CAL_RESISTANCE2 = 0x2090; // uint16, read/write
        public const uint CAL_RESISTANCE3 = 0x2092; // uint16, read/write
        public const uint CAL_RESISTANCE4 = 0x2094; // uint16, read/write
        public const uint CAL_RESISTANCE5 = 0x2096; // uint16, read/write
        public const uint CAL_RESISTANCE6 = 0x2098; // uint16, read/write
        public const uint CAL_RESISTANCE7 = 0x209a; // uint16, read/write
        public const uint CAL_XTALK_VALID = 0x209c; // uint16, read/write : Set to indicate `cal_xtalk_*` calibration should be used
            public const uint CAL_XTALK_VALID_NOT_SET = 0x0; // State
            public const uint CAL_XTALK_VALID_OK = 0x1; // State
        public const uint CAL_XTALK_ALPHA_GRAD_X = 0x20a4; // int16, read/write
        public const uint CAL_XTALK_ALPHA_GRAD_Y = 0x20a6; // int16, read/write
        public const uint CAL_XTALK_ALPHA_OFFSET_X = 0x20a8; // int16, read/write
        public const uint CAL_XTALK_ALPHA_OFFSET_Y = 0x20aa; // int16, read/write
        public const uint CAL_XTALK_BETA_GRAD_X = 0x20ac; // int16, read/write
        public const uint CAL_XTALK_BETA_GRAD_Y = 0x20ae; // int16, read/write
        public const uint CAL_XTALK_BETA_OFFSET_X = 0x20b0; // int32, read/write
        public const uint CAL_XTALK_BETA_OFFSET_Y = 0x20b4; // int32, read/write
        public const uint CAL_POS_EST_OFFSET_VALID = 0x20b8; // uint16, read/write : Set to indicate `cal_pos_est_offset` calibration should be used
            public const uint CAL_POS_EST_OFFSET_VALID_NOT_SET = 0x0; // State
            public const uint CAL_POS_EST_OFFSET_VALID_OK = 0x1; // State
        public const uint CAL_POS_EST_OFFSET_X = 0x20ba; // int16, read/write
        public const uint CAL_POS_EST_OFFSET_Y = 0x20bc; // int16, read/write
        public const uint CAL_POS_EST_OFFSET_Z = 0x20be; // int16, read/write
        public const uint CAL_TILT_CORRECTION_VALID = 0x20c0; // uint16, read/write : Set to indicate `cal_tilt_calibration` calibration should be used
            public const uint CAL_TILT_CORRECTION_VALID_NOT_SET = 0x0; // State
            public const uint CAL_TILT_CORRECTION_VALID_OK = 0x1; // State
        public const uint CAL_TILT_CORRECTION_RX = 0x20c4; // int16, read/write
        public const uint CAL_TILT_CORRECTION_RY = 0x20c6; // int16, read/write
        public const uint CAL_AF_DEPENDENT_GG_VALID = 0x20c8; // uint16, read/write : Set to indicate `cal_af_dependent_gg_*` calibration should be used
            public const uint CAL_AF_DEPENDENT_GG_VALID_NOT_SET = 0x0; // State
            public const uint CAL_AF_DEPENDENT_GG_VALID_OK = 0x1; // State
        public const uint CAL_AF_DEPENDENT_GG_X = 0x20cc; // int32, read/write
        public const uint CAL_AF_DEPENDENT_GG_Y = 0x20d0; // int32, read/write
        public const uint CAL_4WD_ADJ_VALID = 0x20d4; // uint16, read/write : Set to indicate `cal_tg*_4wd_adj_*` calibration should be used
            public const uint CAL_4WD_ADJ_VALID_NOT_SET = 0x0; // State
            public const uint CAL_4WD_ADJ_VALID_OK = 0x1; // State
        public const uint CAL_TG0_4WD_ADJ_RX = 0x20d8; // int16, read/write
        public const uint CAL_TG0_4WD_ADJ_RY = 0x20da; // int16, read/write
        public const uint CAL_TG0_4WD_ADJ_Z = 0x20dc; // int16, read/write
        public const uint CAL_TG1_4WD_ADJ_RX = 0x20de; // int16, read/write
        public const uint CAL_TG1_4WD_ADJ_RY = 0x20e0; // int16, read/write
        public const uint CAL_TG1_4WD_ADJ_Z = 0x20e2; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_VALID = 0x20e4; // uint16, read/write : Set to indicate the `cal_af_dependent_phase_*` calibration should be used
            public const uint CAL_AF_DEPENDENT_PHASE_VALID_NOT_SET = 0x0; // State
            public const uint CAL_AF_DEPENDENT_PHASE_VALID_OK = 0x1; // State
        public const uint CAL_AF_DEPENDENT_PHASE_FEATURES = 0x20e6; // uint16, read/write
            public const uint CAL_AF_DEPENDENT_PHASE_FEATURES_DISABLED = 0x0; // State : Set to indicate 'mp_phase_comp' registers used
            public const uint CAL_AF_DEPENDENT_PHASE_FEATURES_ENABLED = 0x1; // State : Set to indicate 'cal_af_dependent_phase' registers used
            public const uint CAL_AF_DEPENDENT_PHASE_FEATURES_SUMMED = 0x2; // State : Set to indicate sum of 'mp_phase_comp' and 'cal_af_dependent_phase' registers used
        public const uint CAL_AF_DEPENDENT_PHASE_GRAD_X_POS = 0x20e8; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_GRAD_X_NEG = 0x20ea; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_GRAD_Y_POS = 0x20ec; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_GRAD_Y_NEG = 0x20ee; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_OFFSET_X = 0x20f0; // int16, read/write
        public const uint CAL_AF_DEPENDENT_PHASE_OFFSET_Y = 0x20f2; // int16, read/write
        public const uint CAL_AF_SA_GAIN_VALID = 0x20f4; // uint16, read/write : Set to indicate `cal_af_sa_gain` calibration should be used
            public const uint CAL_AF_SA_GAIN_VALID_NOT_SET = 0x0; // State
            public const uint CAL_AF_SA_GAIN_VALID_OK = 0x1; // State
        public const uint CAL_AF_SA_GAIN = 0x20f6; // uint16, read/write
        public const uint CAL_SENSITIVITY_TUNING_VALID = 0x2100; // uint16, read/write : Set to indicate `cal_sensitivity_tuning` calibration should be used
            public const uint CAL_SENSITIVITY_TUNING_VALID_NOT_SET = 0x0; // State
            public const uint CAL_SENSITIVITY_TUNING_VALID_OK = 0x1; // State
        public const uint CAL_SENSITIVITY_X = 0x2102; // int16, read/write
        public const uint CAL_SENSITIVITY_Y = 0x2104; // int16, read/write
        public const uint CAL_SENSITIVITY_Z = 0x2106; // int16, read/write
        public const uint CAL_AF_HYSTERESIS_VALID = 0x2108; // uint16, read/write : Set to indicate `cal_af_hysteresis_*` calibration should be used
            public const uint CAL_AF_HYSTERESIS_VALID_NOT_SET = 0x0; // State
            public const uint CAL_AF_HYSTERESIS_VALID_OK = 0x1; // State
        public const uint CAL_AF_HYSTERESIS_MIX_WEIGHT = 0x210a; // int16, read/write
        public const uint CAL_RSLACK_AVERAGE_VALID = 0x211c; // uint16, read/write : Set to indicate `cal_rslack_average` calibration should be used
            public const uint CAL_RSLACK_AVERAGE_VALID_NOT_SET = 0x0; // State
            public const uint CAL_RSLACK_AVERAGE_VALID_OK = 0x1; // State
        public const uint CAL_RSLACK_AVERAGE = 0x211e; // int16, read/write
        public const uint SIGGEN_OUTPUT_X = 0x2126; // int16, read-only : Output of signal generator on channel X
        public const uint SIGGEN_OUTPUT_Y = 0x2128; // int16, read-only : Output of signal generator on channel Y
        public const uint SIGGEN_OUTPUT_Z = 0x212a; // int16, read-only : Output of signal generator on channel Z
        public const uint SIGGEN_FEATURES = 0x2130; // uint16, read/write : Signal generator behaviour control
            public const uint SIGGEN_FEATURES_ENABLE = 0x1; // Bitfield : Set to enable
            public const uint SIGGEN_FEATURES_GYROFILTER_INPUT = 0x2; // Bitfield : Set to route to motion processing input
        public const uint SIGGEN_FREQ = 0x2132; // uint16 Q9.7, read/write : Set signal frequency of all channels in units of Hz. Maximum supported frequency is ~512 Hz.
        public const uint SIGGEN_AMPLITUDE_X = 0x213a; // int16, read/write : Set signal output amplitude on channel X
        public const uint SIGGEN_AMPLITUDE_Y = 0x213c; // int16, read/write : Set signal output amplitude on channel Y
        public const uint SIGGEN_AMPLITUDE_Z = 0x213e; // int16, read/write : Set signal output amplitude on channel Z
        public const uint SIGGEN_PHASE_X = 0x2146; // uint16, read/write : Set phase lead on channel X in units of 360/65536 degrees
        public const uint SIGGEN_PHASE_Y = 0x2148; // uint16, read/write : Set phase lead on channel Y in units of 360/65536 degrees
        public const uint SIGGEN_PHASE_Z = 0x214a; // uint16, read/write : Set phase lead on channel Z in units of 360/65536 degrees
        public const uint SIGGEN_WAVEFORM_X = 0x2152; // uint16, read/write : Set waveform type for channel X
            public const uint SIGGEN_WAVEFORM_X_SINE = 0x0; // State
            public const uint SIGGEN_WAVEFORM_X_TRIANGLE = 0x1; // State
            public const uint SIGGEN_WAVEFORM_X_SQUARE = 0x2; // State
            public const uint SIGGEN_WAVEFORM_X_SAWTOOTH = 0x3; // State
        public const uint SIGGEN_WAVEFORM_Y = 0x2154; // uint16, read/write : Set waveform type for channel Y
            public const uint SIGGEN_WAVEFORM_Y_SINE = 0x0; // State
            public const uint SIGGEN_WAVEFORM_Y_TRIANGLE = 0x1; // State
            public const uint SIGGEN_WAVEFORM_Y_SQUARE = 0x2; // State
            public const uint SIGGEN_WAVEFORM_Y_SAWTOOTH = 0x3; // State
        public const uint SIGGEN_WAVEFORM_Z = 0x2156; // uint16, read/write : Set waveform type for channel Z
            public const uint SIGGEN_WAVEFORM_Z_SINE = 0x0; // State
            public const uint SIGGEN_WAVEFORM_Z_TRIANGLE = 0x1; // State
            public const uint SIGGEN_WAVEFORM_Z_SQUARE = 0x2; // State
            public const uint SIGGEN_WAVEFORM_Z_SAWTOOTH = 0x3; // State
        public const uint SIGGEN_OFFSET_X = 0x215e; // int16, read/write : Set offset for channel X
        public const uint SIGGEN_OFFSET_Y = 0x2160; // int16, read/write : Sets offset for channel Y
        public const uint SIGGEN_OFFSET_Z = 0x2162; // int16, read/write : Set offset for channel Z
        public const uint DEBUG_STATUS = 0x2174; // uint16, read-only : Flags to indicate overall status for debugging purpose
            public const uint DEBUG_STATUS_SERVO_CTRL = 0x1; // Bitfield : Indicates the servo loop is on
            public const uint DEBUG_STATUS_GYRO_POLL = 0x2; // Bitfield : Indicates gyro polling is on
            public const uint DEBUG_STATUS_GYRO_MP = 0x4; // Bitfield : Indicates gyro filter/motion processing is on
            public const uint DEBUG_STATUS_OIS = 0x8; // Bitfield : Indicates OIS is on
            public const uint DEBUG_STATUS_CALIBRATE_GYRO = 0x10; // Bitfield : Indicates gyro offset calibration is in progress
            public const uint DEBUG_STATUS_APOIS = 0x200; // Bitfield : Indicates that APOIS is on
            public const uint DEBUG_STATUS_PLL_ERROR = 0x400; // Bitfield : Indicates PLL did not initialise correctly
            public const uint DEBUG_STATUS_EIS = 0x800; // Bitfield : Indicates EIS is on
            public const uint DEBUG_STATUS_MCLK_MISSING_ERROR = 0x1000; // Bitfield : Indicates MCLK was missing
            public const uint DEBUG_STATUS_HOIS = 0x4000; // Bitfield : Indicates Hyper OIS is on
        public const uint SERVO_CTRL = 0x2176; // uint16, read/write : Servo loop control
            public const uint SERVO_CTRL_ENABLE = 0x1; // Bitfield : Set to enable servo loop
            public const uint SERVO_CTRL_ERROR = 0x800; // Bitfield : Indicates error occurred servicing the command
            public const uint SERVO_CTRL_BUSY = 0x2000; // Bitfield : Indicates command is being serviced
            public const uint SERVO_CTRL_SUCCESS = 0x4000; // Bitfield : Indicates command is done
            public const uint SERVO_CTRL_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint GYRO_CTRL = 0x2178; // uint16, read/write : Gyro control
            public const uint GYRO_CTRL_POLL_ENABLE = 0x1; // Bitfield : Set to enable gyro polling
            public const uint GYRO_CTRL_MP_ENABLE = 0x2; // Bitfield : Set to enable gyro filter/motion processing
            public const uint GYRO_CTRL_SERVO_ENABLE = 0x4; // Bitfield : Secondary enable servo on. Set to enable servo loop. This is logically OR'd with servo_ctrl_enable. For handset OIS software.
            public const uint GYRO_CTRL_APOIS_ENABLE = 0x8; // Bitfield : Set to enable APOIS mode
            public const uint GYRO_CTRL_ERROR = 0x800; // Bitfield : Indicates error occurred servicing the command
            public const uint GYRO_CTRL_BUSY = 0x2000; // Bitfield : Indicates command is being serviced
            public const uint GYRO_CTRL_SUCCESS = 0x4000; // Bitfield : Indicates command is done
            public const uint GYRO_CTRL_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint GYRO_CALIB = 0x217a; // uint16, read/write : Gyro calibration control
            public const uint GYRO_CALIB_ENABLE = 0x1; // Bitfield : Set to initiate gyro offset calibration
            public const uint GYRO_CALIB_ERROR = 0x800; // Bitfield : Indicates error occurred servicing the command
            public const uint GYRO_CALIB_BUSY = 0x2000; // Bitfield : Indicates command is being serviced
            public const uint GYRO_CALIB_SUCCESS = 0x4000; // Bitfield : Indicates command is done
            public const uint GYRO_CALIB_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint CALIB_FLASH = 0x217c; // uint16, read/write : Calibration flash control
            public const uint CALIB_FLASH_ERASE = 0x1; // Bitfield : Set to erase flash calibration region
            public const uint CALIB_FLASH_LOAD = 0x2; // Bitfield : Set to load calibration from flash calibration region
            public const uint CALIB_FLASH_SAVE = 0x4; // Bitfield : Set to save calibration to flash calibration region
            public const uint CALIB_FLASH_APPLY = 0x8; // Bitfield : Set to force apply current RAM calibration
            public const uint CALIB_FLASH_ERROR = 0x800; // Bitfield : Indicates error occurred servicing the command
            public const uint CALIB_FLASH_BUSY = 0x2000; // Bitfield : Indicates command is being serviced
            public const uint CALIB_FLASH_SUCCESS = 0x4000; // Bitfield : Indicates command is done
            public const uint CALIB_FLASH_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint LP_CTRL = 0x217e; // uint16, read/write : Power mode control
            public const uint LP_CTRL_ENABLE = 0x1; // Bitfield : Set to enable low power mode. Clear to exit low power mode.
            public const uint LP_CTRL_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent. Reading will result in exit low power mode.
        public const uint EIS_CTRL = 0x2180; // uint16, read/write : EIS control
            public const uint EIS_CTRL_ENABLE = 0x1; // Bitfield : Set to enable EIS logging, clear to disable
            public const uint EIS_CTRL_ERROR = 0x800; // Bitfield : Indicates error occurred servicing the command
            public const uint EIS_CTRL_BUSY = 0x2000; // Bitfield : Indicates command is being serviced
            public const uint EIS_CTRL_SUCCESS = 0x4000; // Bitfield : Indicates command is done
            public const uint EIS_CTRL_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint USER_INPUT_POS_X = 0x218a; // int16, read/write : Position demand on channel X, in position units, write with bit 15 set to 0
            public const uint USER_INPUT_POS_X_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint USER_INPUT_POS_Y = 0x218c; // int16, read/write : Position demand on channel Y, in position units, write with bit 15 set to 0
            public const uint USER_INPUT_POS_Y_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint USER_INPUT_POS_Z = 0x218e; // int16, read/write : Position demand on channel Z, in position units, write with bit 15 set to 0
            public const uint USER_INPUT_POS_Z_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint GYRO_RAW_X = 0x40190; // int16, read-only : Gyro reading for X axis
        public const uint GYRO_RAW_Y = 0x40192; // int16, read-only : Gyro reading for Y axis
        public const uint GYRO_RAW_Z = 0x40194; // int16, read-only : Gyro reading for Z axis
        public const uint ACC_RAW_X = 0x40196; // int16, read-only : Accelerometer reading for X axis
        public const uint ACC_RAW_Y = 0x40198; // int16, read-only : Accelerometer reading for Y axis
        public const uint ACC_RAW_Z = 0x4019a; // int16, read-only : Accelerometer reading for Z axis
        public const uint MP_OUTPUT_X = 0x4019c; // int16, read-only : Motion processing output channels associated with shake around actuator axes
        public const uint MP_OUTPUT_Y = 0x4019e; // int16, read-only : Motion processing output channels associated with shake around actuator axes
        public const uint MP_OUTPUT_Z = 0x401a0; // int16, read-only : Motion processing output channels associated with shake around actuator axes
        public const uint MP_GYRO_BIAS_ACCURACY = 0x21a2; // int8, read-only : Gyro offset calibration accuracy level from the motion processing
            public const uint MP_GYRO_BIAS_ACCURACY_UNRELIABLE = 0x0; // State : Uncalibrated or unreliable
            public const uint MP_GYRO_BIAS_ACCURACY_LOW = 0x1; // State : Low
            public const uint MP_GYRO_BIAS_ACCURACY_MEDIUM = 0x2; // State : Medium
            public const uint MP_GYRO_BIAS_ACCURACY_HIGH = 0x3; // State : High
        public const uint MP_MOTION_LEVEL = 0x21a3; // uint8, read/write : Shake level estimated by motion processing
            public const uint MP_MOTION_LEVEL_HIGH = 0x0; // State : Full
            public const uint MP_MOTION_LEVEL_MID = 0x1; // State : Middle
            public const uint MP_MOTION_LEVEL_LOW = 0x2; // State : Lowest
        public const uint MP_STROKE_WIN_X = 0x21a4; // int16, read-only : Stroke window input values to motion processing, in position units
        public const uint MP_STROKE_WIN_Y = 0x21a6; // int16, read-only : Stroke window input values to motion processing, in position units
        public const uint MP_STROKE_WIN_Z = 0x21a8; // int16, read-only : Stroke window input values to motion processing, in position units
        public const uint MP_LIB_VER0 = 0x21aa; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER1 = 0x21ab; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER2 = 0x21ac; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER3 = 0x21ad; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER4 = 0x21ae; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER5 = 0x21af; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER6 = 0x21b0; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER7 = 0x21b1; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER8 = 0x21b2; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER9 = 0x21b3; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER10 = 0x21b4; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER11 = 0x21b5; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER12 = 0x21b6; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER13 = 0x21b7; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER14 = 0x21b8; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER15 = 0x21b9; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER16 = 0x21ba; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER17 = 0x21bb; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER18 = 0x21bc; // uint8, read-only : Motion processing library version
        public const uint MP_LIB_VER19 = 0x21bd; // uint8, read-only : Motion processing library version
        public const uint MP_FREEFALL_CTRL = 0x21be; // uint8, read/write : Motion processing freefall detection control
            public const uint MP_FREEFALL_CTRL_ENABLE = 0x1; // Bitfield : Set to enable motion processing freefall detection feature, clear to disable
        public const uint MP_FREEFALL_EVENT = 0x21bf; // uint8, read-only : Motion processing freefall status
            public const uint MP_FREEFALL_EVENT_FREEFALL = 0x1; // Bitfield : Freefall detected
            public const uint MP_FREEFALL_EVENT_DEBOUNCE = 0x2; // Bitfield : Debouncer active
            public const uint MP_FREEFALL_EVENT_LOW_G = 0x4; // Bitfield : Low gravity detected
            public const uint MP_FREEFALL_EVENT_HIGH_G = 0x8; // Bitfield : High gravity detected
            public const uint MP_FREEFALL_EVENT_SHOCK = 0x10; // Bitfield : Shock detected
        public const uint MP_FREEFALL_DURATION = 0x401c0; // uint16, read-only : Freefall duration estimate in milliseconds. Updated in realtime during freefall.
        public const uint MP_FREEFALL_HEIGHT = 0x401c2; // uint16, read-only : Freefall height estimate in millimetres. Updated in realtime during freefall.
        public const uint MP_LIB_RET_CODE = 0x21c4; // uint8, read-only : Motion processing library status
            public const uint MP_LIB_RET_CODE_SUCCESS = 0x0; // State : Success
            public const uint MP_LIB_RET_CODE_AUTHENTIFICATION_ERROR = 0x1; // State : Authentification error
            public const uint MP_LIB_RET_CODE_TIME_OUT = 0x2; // State : Timeout
            public const uint MP_LIB_RET_CODE_FLASH_LOCKED = 0x3; // State : Flash access error
            public const uint MP_LIB_RET_CODE_UNSUPPORTED_GYRO = 0x4; // State : Unsupported gyro
            public const uint MP_LIB_RET_CODE_UNINITIALIZED = 0x6; // State : Uninitialized
            public const uint MP_LIB_RET_CODE_INCOMPATIBLE_SYSTEM_DELAY = 0x7; // State : Incompatible system delay
            public const uint MP_LIB_RET_CODE_UNSUPPORTED = 0x8; // State : Unsupported feature
            public const uint MP_LIB_RET_CODE_STOP = 0xb; // State : Motion processing stopped
            public const uint MP_LIB_RET_CODE_UNKNOWN_ISSUE = 0xff; // State : Unknown issue
        public const uint MP_FREEFALL_COUNT = 0x401c6; // uint16, read-only : Number of freefall occurrences since the last servo on
        public const uint MP_LENS_EFL = 0x21cc; // int32 Q19.12, read/write : EFL of the lens used to define degree to um conversion
        public const uint MP_SHAKE_LEVEL_THRESHOLDS0 = 0x21de; // uint16, read/write : raw thresholds below which tremors are for configurable durations to pass to associated shake level. 1dps = 131 in raw units
        public const uint MP_SHAKE_LEVEL_THRESHOLDS1 = 0x21e0; // uint16, read/write : raw thresholds below which tremors are for configurable durations to pass to associated shake level. 1dps = 131 in raw units
        public const uint MP_SHAKE_LEVEL_DURATIONS0 = 0x21e2; // uint16, read/write : durations in miliseconds for which tremors are below each threshold to pass to associated shake level
        public const uint MP_SHAKE_LEVEL_DURATIONS1 = 0x21e4; // uint16, read/write : durations in miliseconds for which tremors are below each threshold to pass to associated shake level
        public const uint TRIPOD_RAMP_DOWN = 0x21f2; // uint16, read/write : Duration of tripod ramp down in ms, 0 turns off the feature
        public const uint EIS_MODE = 0x21f6; // uint16, read/write : Select EIS mode of operation
            public const uint EIS_MODE_VSYNC = 0x0; // State : Use VSync signal to synchronise AP and firmware
            public const uint EIS_MODE_QTIMER = 0x1; // State : Use QTimer protocol to synchronise AP and firmware
            public const uint EIS_MODE_PACKET_TRIGGER = 0x2; // State : Use packet trigger protocol to synchronise AP and firmware
        public const uint EIS_SAMPLE_FORMAT = 0x21f8; // uint16, read/write : EIS sample fields configuration
            public const uint EIS_SAMPLE_FORMAT_POS_RX = 0x1; // Bitfield : Position estimate RX
            public const uint EIS_SAMPLE_FORMAT_POS_RY = 0x2; // Bitfield : Position estimate RY
            public const uint EIS_SAMPLE_FORMAT_POS_RZ = 0x4; // Bitfield : Position estimate RZ
            public const uint EIS_SAMPLE_FORMAT_POS_X = 0x8; // Bitfield : Position estimate X
            public const uint EIS_SAMPLE_FORMAT_POS_Y = 0x10; // Bitfield : Position estimate Y
            public const uint EIS_SAMPLE_FORMAT_POS_Z = 0x20; // Bitfield : Position estimate Z
            public const uint EIS_SAMPLE_FORMAT_GYRO_X = 0x40; // Bitfield : Raw gyro X
            public const uint EIS_SAMPLE_FORMAT_GYRO_Y = 0x80; // Bitfield : Raw gyro Y
            public const uint EIS_SAMPLE_FORMAT_GYRO_Z = 0x100; // Bitfield : Raw gyro Z
            public const uint EIS_SAMPLE_FORMAT_ACC_X = 0x200; // Bitfield : Raw acceleration X
            public const uint EIS_SAMPLE_FORMAT_ACC_Y = 0x400; // Bitfield : Raw acceleration Y
            public const uint EIS_SAMPLE_FORMAT_ACC_Z = 0x800; // Bitfield : Raw acceleration Z
        public const uint EIS_SAMPLE_PERIOD = 0x21fa; // uint16, read/write : EIS sample period, in units of 0.1 ms
        public const uint EIS_DATA_CTRL = 0x21fc; // uint16, read/write : EIS data 'chunk' selection. When requesting the last chunk, set the most significant bit to indicate to the firmware that it has finished reading the current frame.
            public const uint EIS_DATA_CTRL_SELECT = 0x3; // Bitfield : Set to select EIS data chunk
                public const uint EIS_DATA_CTRL_SELECT_CHUNK_1 = 0x1; // Bitfield state
                public const uint EIS_DATA_CTRL_SELECT_CHUNK_2 = 0x2; // Bitfield state
                public const uint EIS_DATA_CTRL_SELECT_CHUNK_3 = 0x3; // Bitfield state
            public const uint EIS_DATA_CTRL_FRAME_CLEAR = 0x8000; // Bitfield : When requesting the last chunk, set to indicate to the firmware that it has finished reading the current frame
                public const uint EIS_DATA_CTRL_FRAME_CLEAR_NOT_REQUESTED = 0x0; // Bitfield state
                public const uint EIS_DATA_CTRL_FRAME_CLEAR_REQUESTED = 0x8000; // Bitfield state
        public const uint EIS_PACKET_TRIGGER = 0x21fe; // uint16, read/write : Packet trigger set by host to start/stop EIS packet
        public const uint EIS_VSYNC_TIME = 0x2200; // uint16, read-only : Time of last VSync pulse since enabling servo loop, in units of 0.1 ms
        public const uint EIS_NUM_SAMPLES = 0x2202; // uint16, read/write : Maximum number of bytes allowed in an EIS frame has to be multiple of 2 bytes. Header size is 12 bytes for packet trigger mode, 6 bytes for VSync mode, and 10 bytes for Qtimer mode. Max value can be 240, any value less than header size + minimum data will default to 240 bytes.
        public const uint EIS_QTIMER_WRITE = 0x2208; // uint64, read/write : QTimer value in units of nanoseconds set by host. The new value written must be different from the previous one.
        public const uint EIS_DATA0 = 0x2210; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA1 = 0x2212; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA2 = 0x2214; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA3 = 0x2216; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA4 = 0x2218; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA5 = 0x221a; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA6 = 0x221c; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA7 = 0x221e; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA8 = 0x2220; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA9 = 0x2222; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA10 = 0x2224; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA11 = 0x2226; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA12 = 0x2228; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA13 = 0x222a; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA14 = 0x222c; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA15 = 0x222e; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA16 = 0x2230; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA17 = 0x2232; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA18 = 0x2234; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA19 = 0x2236; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA20 = 0x2238; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA21 = 0x223a; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA22 = 0x223c; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA23 = 0x223e; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA24 = 0x2240; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA25 = 0x2242; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA26 = 0x2244; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA27 = 0x2246; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA28 = 0x2248; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA29 = 0x224a; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA30 = 0x224c; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA31 = 0x224e; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA32 = 0x2250; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA33 = 0x2252; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA34 = 0x2254; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA35 = 0x2256; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA36 = 0x2258; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA37 = 0x225a; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA38 = 0x225c; // int16, read-only : EIS data 'chunk' buffer
        public const uint EIS_DATA39 = 0x225e; // int16, read-only : EIS data 'chunk' buffer
        public const uint AF_TARGET = 0x2262; // uint16, read/write : AF target position
            public const uint AF_TARGET_UPDATE = 0x8000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint SET_PWM_FREQUENCY = 0x2264; // uint32, write-only : Set desired PWM frequency
            public const uint SET_PWM_FREQUENCY_UPDATE = 0x80000000; // Bitfield : Set by the firmware to indicate that it is ready to receive a command. Cleared by the host to indicate the command has been sent.
        public const uint VSYNC_CTRL = 0x2282; // uint16, read/write : VSync control
            public const uint VSYNC_CTRL_DISABLE = 0x0; // State : Disable VSync interrupt
            public const uint VSYNC_CTRL_ENABLE_RISING_EDGE = 0x1; // State : Enable VSync interrupt on rising edge
            public const uint VSYNC_CTRL_ENABLE_FALLING_EDGE = 0x2; // State : Enable VSync interrupt on falling edge
        public const uint VSYNC_COUNT = 0x2284; // uint16, read-only : Counter incremented on each VSync pulse
        public const uint BUF_GYRO_RAW_X = 0x229c; // int16, read-only : Buffered gyro X data for direct access
        public const uint BUF_GYRO_RAW_Y = 0x229e; // int16, read-only : Buffered gyro Y data for direct access
        public const uint BUF_GYRO_RAW_Z = 0x22a0; // int16, read-only : Buffered gyro Z data for direct access
        public const uint BUF_ACC_RAW_X = 0x22a2; // int16, read-only : Buffered accel X data for direct access
        public const uint BUF_ACC_RAW_Y = 0x22a4; // int16, read-only : Buffered accel Y data for direct access
        public const uint BUF_ACC_RAW_Z = 0x22a6; // int16, read-only : Buffered accel Z data for direct access
        public const uint BUF_POS_EST_X = 0x22ae; // int16, read-only : Buffered lens position X data for direct access
        public const uint BUF_POS_EST_Y = 0x22b0; // int16, read-only : Buffered lens position Y data for direct access
        public const uint BUF_POS_EST_Z = 0x22b2; // int16, read-only : Buffered lens position Z data for direct access
        public const uint BUF_INPUT_POS_X = 0x22ba; // int16, read-only : Buffered position demand in X for direct access
        public const uint BUF_INPUT_POS_Y = 0x22bc; // int16, read-only : Buffered position demand in Y for direct access
        public const uint BUF_INPUT_POS_Z = 0x22be; // int16, read-only : Buffered position demand in Z for direct access
        public const uint BUF_MP_OUTPUT_X = 0x22c0; // int16, read-only : Buffered MP output in X for direct access
        public const uint BUF_MP_OUTPUT_Y = 0x22c2; // int16, read-only : Buffered MP output in Y for direct access
        public const uint BUF_MP_OUTPUT_Z = 0x22c4; // int16, read-only : Buffered MP output in Z for direct access
        public const uint MP_FREEFALL_LOW_G_THRESHOLD = 0x2316; // uint16 Q4.12, read/write : Low gravity threshold for freefall in units of G
        public const uint HEARTBEAT = 0x2318; // uint16, read-only : System heartbeat counter
        public const uint HOIS_CTRL = 0x231a; // uint16, read/write : Hyper OIS control
            public const uint HOIS_CTRL_ENABLE = 0x1; // Bitfield : Set to enable hyper OIS
                public const uint HOIS_CTRL_ENABLE_HOIS_DISABLED = 0x0; // Bitfield state
                public const uint HOIS_CTRL_ENABLE_HOIS_ENABLED = 0x1; // Bitfield state
            public const uint HOIS_CTRL_FULL_FRAME_RETURN = 0x4; // Bitfield : Set to enable hyper OIS full frame return mode
                public const uint HOIS_CTRL_FULL_FRAME_RETURN_FULL_FRAME_RETURN_DISABLED = 0x0; // Bitfield state
                public const uint HOIS_CTRL_FULL_FRAME_RETURN_FULL_FRAME_RETURN_ENABLED = 0x4; // Bitfield state
            public const uint HOIS_CTRL_FULL_FRAME_RETURN_TRIGGER_MODE = 0x8; // Bitfield : Select trigger mode for full frame return function
                public const uint HOIS_CTRL_FULL_FRAME_RETURN_TRIGGER_MODE_AUTOMATIC = 0x0; // Bitfield state
                public const uint HOIS_CTRL_FULL_FRAME_RETURN_TRIGGER_MODE_MANUAL = 0x8; // Bitfield state
            public const uint HOIS_CTRL_FRAME_SYNC_MODE = 0x10; // Bitfield : Frame synchronisation mode. Bit set if using HOIS_TRIGGER register
                public const uint HOIS_CTRL_FRAME_SYNC_MODE_USE_VSYNC = 0x0; // Bitfield state
                public const uint HOIS_CTRL_FRAME_SYNC_MODE_USE_HOIS_TRIGGER = 0x10; // Bitfield state
        public const uint HOIS_DELAY = 0x231c; // uint16, read/write : Delay between VSync event and start of centring, in units of 0.1 ms
        public const uint HOIS_DURATION = 0x231e; // uint16, read/write : Duration for centring, in units of 0.1 ms
        public const uint HOIS_STATUS = 0x2320; // uint16, read-only : Hyper OIS status
            public const uint HOIS_STATUS_CENTRING = 0x1; // Bitfield : Centring
            public const uint HOIS_STATUS_DELAY = 0x2; // Bitfield : Delay
            public const uint HOIS_STATUS_FULL_FRAME_RETURN = 0x8; // Bitfield : Indicates full frame return is active
        public const uint HOIS_OFFSET_VALID = 0x2322; // uint16, read/write : Set by the firmware to indicate the HOIS offsets have been updated. Cleared by the firmware or by the host that is running the motion processing, to indicate the offset have been applied.
            public const uint HOIS_OFFSET_VALID_HOIS_OFFSET_INVALID = 0x0; // State : HOIS offset value is not valid
            public const uint HOIS_OFFSET_VALID_HOIS_OFFSET_VALID = 0x1; // State : HOIS offset value is valid
        public const uint HOIS_OFFSET_X = 0x2324; // int16, read/write : Hyper OIS offset X
        public const uint HOIS_OFFSET_Y = 0x2326; // int16, read/write : Hyper OIS offset Y
        public const uint HOIS_FRAME_RETURN_THRESHOLD = 0x2338; // uint16, read/write : Offset from nominal stroke limit that triggers return frame, in position units
        public const uint HOIS_FRAME_RETURN_TRIGGER = 0x233a; // uint16, read/write : Manual frame return mode trigger, write 0x01 to trigger a return-to-centre during the next frame. Cleared to 0x00 by the Firmware
        public const uint HOIS_FRAME_RETURN_RATE_LIMIT = 0x233c; // uint16, read/write : Duration time required before a return frame can trigger again, in units of 0.1 ms
        public const uint SPI_CS_COUNT = 0x2340; // uint16, read-only : Counter incremented on each SPI chip select signal
        public const uint HANDSET_PHOTO_TRIGGER = 0x2342; // uint16, read/write : Handset photo trigger, set before preview and clear before exposure
        public const uint MP_PREVIEW_STROKE_MARGIN = 0x2344; // int16, read/write : Value subtracted from motion processing stroke window for preview mode, in position units
        public const uint MP_TRIPOD = 0x2360; // uint8, read-only : Indicates if the device is in tripod mode
            public const uint MP_TRIPOD_DETECTED = 0x1; // Bitfield : Motion processing tripod mode state
                public const uint MP_TRIPOD_DETECTED_NOT_DETECTED = 0x0; // Bitfield state : Motion processing tripod mode not active
                public const uint MP_TRIPOD_DETECTED_DETECTED = 0x1; // Bitfield state : Motion processing tripod mode active
            public const uint FREEFALL_STATE = 0x2362; // uint16, read/write : Freefall protection behaviour set by motion processing
            public const uint FREEFALL_STATE_ENABLE = 0x1; // Bitfield : Set to trigger freefall protection behaviour, clear to return to normal operation
        public const uint HOIS_TRIGGER = 0x236a; // uint16, read/write : Trigger synchronisation in I2C synchronisation mode
        public const uint WIRE_STATUS = 0x2510; // uint16, read-only : Indicates whether an open/closed circuit was detected for each wire
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_0 = 0x1; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_0 = 0x2; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_1 = 0x4; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_1 = 0x8; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_2 = 0x10; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_2 = 0x20; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_3 = 0x40; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_3 = 0x80; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_4 = 0x100; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_4 = 0x200; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_5 = 0x400; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_5 = 0x800; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_6 = 0x1000; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_6 = 0x2000; // Bitfield
            public const uint WIRE_STATUS_OPENCIRCUIT_WIRE_7 = 0x4000; // Bitfield
            public const uint WIRE_STATUS_SHORTCIRCUIT_WIRE_7 = 0x8000; // Bitfield
        public const uint THERMISTOR_STATUS = 0x2512; // uint16, read-only : Indicates an invalid temperature reading
        public const uint THERMISTOR_STATUS_TEMPERATURE_INVALID = 0x1; // Bitfield : Invalid thermistor reading
        public const uint VOLTAGE_STATUS = 0x2514; // uint16, read-only : Indicates actuator supply voltage outside supported range at startup
            public const uint VOLTAGE_STATUS_OVER = 0x1; // Bitfield : Actuator supply voltage was above the maximum error threshold
            public const uint VOLTAGE_STATUS_UNDER = 0x2; // Bitfield : Actuator supply voltage was below the minimum error threshold
            public const uint VOLTAGE_STATUS_WARNING_OVER = 0x4; // Bitfield : Actuator supply voltage was above the maximum warning threshold
            public const uint VOLTAGE_STATUS_WARNING_UNDER = 0x8; // Bitfield : Actuator supply voltage was below the minimum warning threshold
        public const uint PDU_STATUS = 0x253c; // uint16, read-only : Power delivery unit status
            public const uint PDU_STATUS_DISABLED = 0x0; // State : Indicates the PDU is disabled
            public const uint PDU_STATUS_ENABLED = 0x1; // State : Indicates the PDU is enabled
        public const uint PARAMS_MODE = 0x2570; // uint16, read/write : Bitfield to select operating mode
            public const uint PARAMS_MODE_OPEN_STROKE_LIMITS = 0x1; // Bitfield : Set to increase stroke limits for specific CCM testing mode
                public const uint PARAMS_MODE_OPEN_STROKE_LIMITS_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_OPEN_STROKE_LIMITS_ENABLED = 0x1; // Bitfield state
            public const uint PARAMS_MODE_FRA_OL = 0x2; // Bitfield : Set to enable frequency response analysis (FRA) testing mode
                public const uint PARAMS_MODE_FRA_OL_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_FRA_OL_ENABLED = 0x2; // Bitfield state
            public const uint PARAMS_MODE_TG0_4WD = 0x8; // Bitfield : Set to enable four wire drive mode using tension group 0 (servo must be off when set by host)
                public const uint PARAMS_MODE_TG0_4WD_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_TG0_4WD_ENABLED = 0x8; // Bitfield state
            public const uint PARAMS_MODE_TG1_4WD = 0x10; // Bitfield : Set to enable four wire drive mode using tension group 1 (servo must be off when set by host)
                public const uint PARAMS_MODE_TG1_4WD_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_TG1_4WD_ENABLED = 0x10; // Bitfield state
            public const uint PARAMS_MODE_MOTION_LEVEL = 0x60; // Bitfield : Indicates current motion level (to allow this to be set by the host, motion level mode must be set to manual)
                public const uint PARAMS_MODE_MOTION_LEVEL_HIGH = 0x0; // Bitfield state
                public const uint PARAMS_MODE_MOTION_LEVEL_MID = 0x20; // Bitfield state
                public const uint PARAMS_MODE_MOTION_LEVEL_LOW = 0x40; // Bitfield state
            public const uint PARAMS_MODE_AMS_TESTING = 0x80; // Bitfield : Set to enable AMS testing parameters (servo must be off when set by host)
                public const uint PARAMS_MODE_AMS_TESTING_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_AMS_TESTING_ENABLED = 0x80; // Bitfield state
            public const uint PARAMS_MODE_AMS_STROKE_CAPABILITY_TESTING = 0x100; // Bitfield : Set to enable AMS stroke capability testing parameters (servo must be off when set by host)
                public const uint PARAMS_MODE_AMS_STROKE_CAPABILITY_TESTING_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_AMS_STROKE_CAPABILITY_TESTING_ENABLED = 0x100; // Bitfield state
            public const uint PARAMS_MODE_HOIS_MODE = 0x200; // Bitfield : Indicates current Hyper OIS mode
                public const uint PARAMS_MODE_HOIS_MODE_DISABLED = 0x0; // Bitfield state
                public const uint PARAMS_MODE_HOIS_MODE_ENABLED = 0x200; // Bitfield state
        public const uint SMA_SUPPLY_VOLTAGE = 0x4057c; // uint16, read-only : Measured SMA actuator supply voltage in units of mV
        public const uint SMA_SUPPLY_VOLTAGE_FOR_VOLTAGE_STATUS = 0x40580; // uint16, read-only : Measured SMA actuator supply voltage used for the VOLTAGE_STATUS check, in units of mV
        public const uint INPUT_POS_X = 0x405be; // int16, read/write : Position demand on channel X, in position units
        public const uint INPUT_POS_Y = 0x405c0; // int16, read/write : Position demand on channel Y, in position units
        public const uint INPUT_POS_Z = 0x405c2; // int16, read/write : Position demand on channel Z, in position units
        public const uint POS_EST_X = 0x405ca; // int16, read-only : Estimated lens shift in X
        public const uint POS_EST_Y = 0x405cc; // int16, read-only : Estimated lens shift in Y
        public const uint POS_EST_Z = 0x405ce; // int16, read-only : Estimated lens shift in Z
        public const uint STATUS = 0x25d0; // uint16, read-only : Control status
            public const uint STATUS_SERVO_OFF = 0x0; // State : SMA Control Status - Off
            public const uint STATUS_RUNNING = 0x1; // State : SMA Control Status - Running
            public const uint STATUS_SSLDEBUG = 0x2; // State : SMA control status - Debug Mode
            public const uint STATUS_POWERUP = 0x3; // State : SMA Control Status - Zero-hold power - Power-up
            public const uint STATUS_POWERDOWN = 0x4; // State : SMA Control Status - Zero-hold power - Power-down
            public const uint STATUS_ZEROPOWER = 0x5; // State : SMA Control Status - Zero-hold power - Idle
            public const uint STATUS_WARMINGUP = 0x6; // State : SMA Control Status - Warm-up
            public const uint STATUS_WARMINGDOWN = 0x7; // State : SMA Control Status - Warm-down
            public const uint STATUS_RMIDCAL = 0x8; // State : SMA Control Status - Zero-hold power - Resistance Calibration
        public const uint THERMISTOR = 0x405d2; // int16, read-only : Thermistor temperature in units of 0.1 degC
        public const uint RMID_STATUS = 0x405e4; // uint16, read-only : Flag indicating calibrated rmid value automatically updated
        public const uint PWM_FREQUENCY = 0x29f4; // uint32, read-only : Read back achieved PWM frequency in Hz
        public const uint MOTION_LEVEL_MODE = 0x2a0c; // uint16, read/write : Motion level mode control
            public const uint MOTION_LEVEL_MODE_MANUAL = 0x0; // State : Motion level mode can be switched by the host using params_mode
            public const uint MOTION_LEVEL_MODE_AUTO = 0x1; // State : Motion level mode is switched automatically based on mp_motion_level
        public const uint DRIVE_SCHEME_SYNC_PWM_FREQUENCY0 = 0x2a2c; // uint32, read/write : Frequencies at which to synchronise when using the synchronised drive scheme
        public const uint DRIVE_SCHEME_SYNC_PWM_FREQUENCY1 = 0x2a30; // uint32, read/write : Frequencies at which to synchronise when using the synchronised drive scheme
        public const uint DRIVE_SCHEME_SYNC_PWM_FREQUENCY2 = 0x2a34; // uint32, read/write : Frequencies at which to synchronise when using the synchronised drive scheme
        public const uint DRIVE_SCHEME_SYNC_PWM_FREQUENCY3 = 0x2a38; // uint32, read/write : Frequencies at which to synchronise when using the synchronised drive scheme
        public const uint DRIVE_SCHEME_SYNC_PWM_FREQUENCY4 = 0x2a3c; // uint32, read/write : Frequencies at which to synchronise when using the synchronised drive scheme
        public const uint PWM_MEAS_START_DELAY0 = 0x2a40; // uint16, read/write : PWM measurement start delay in units of 5.2 ns
        public const uint PWM_MEAS_START_DELAY1 = 0x2a42; // uint16, read/write : PWM measurement start delay in units of 5.2 ns
        public const uint PWM_MEAS_START_DELAY2 = 0x2a44; // uint16, read/write : PWM measurement start delay in units of 5.2 ns
        public const uint PWM_MEAS_START_DELAY3 = 0x2a46; // uint16, read/write : PWM measurement start delay in units of 5.2 ns
        public const uint PWM_MEAS_START_DELAY4 = 0x2a48; // uint16, read/write : PWM measurement start delay in units of 5.2 ns
        public const uint SAFE_REGION_INTERVAL0 = 0x2a4c; // uint32, read/write : Time between periods where the image sensor is not sampling in units of 5.2 ns. Only in case VSync is selected
        public const uint SAFE_REGION_INTERVAL1 = 0x2a50; // uint32, read/write : Time between periods where the image sensor is not sampling in units of 5.2 ns. Only in case VSync is selected
        public const uint SAFE_REGION_INTERVAL2 = 0x2a54; // uint32, read/write : Time between periods where the image sensor is not sampling in units of 5.2 ns. Only in case VSync is selected
        public const uint SAFE_REGION_INTERVAL3 = 0x2a58; // uint32, read/write : Time between periods where the image sensor is not sampling in units of 5.2 ns. Only in case VSync is selected
        public const uint SAFE_REGION_INTERVAL4 = 0x2a5c; // uint32, read/write : Time between periods where the image sensor is not sampling in units of 5.2 ns. Only in case VSync is selected
        public const uint TEMPEST_OFFSET = 0x2a68; // int16, read/write : Set calibrated thermistor offset
        public const uint RMID_CAL0 = 0x2a6c; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL1 = 0x2a6e; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL2 = 0x2a70; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL3 = 0x2a72; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL4 = 0x2a74; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL5 = 0x2a76; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL6 = 0x2a78; // uint16, read/write : Calibrated resistance
        public const uint RMID_CAL7 = 0x2a7a; // uint16, read/write : Calibrated resistance
        public const uint RSLACK_AVERAGE_CAL = 0x2aaa; // int16, read/write : Calibrated average slack resistance
        public const uint FLASH_COMMAND = 0x40006b04; // uint16, read/write : Flash control
            public const uint FLASH_COMMAND_POWER_ON = 0x1; // Bitfield : Set to turn on the flash power. 1 indicates busy, 0 indicates done.
            public const uint FLASH_COMMAND_POWER_OFF = 0x2; // Bitfield : Set to turn off the flash power. 1 indicates busy, 0 indicates done.
            public const uint FLASH_COMMAND_CHIP_ERASE = 0x4; // Bitfield : Set to start chip erase. 1 indicates busy, 0 indicates done.
            public const uint FLASH_COMMAND_RESET = 0x8; // Bitfield : Set to start flash controller reset. 1 indicates busy, 0 indicates done.
            public const uint FLASH_COMMAND_DEEP_STANDBY = 0x10; // Bitfield : Set to put flash in deep standby state. 1 indicates busy, 0 indicates done.
            public const uint FLASH_PROGRAM_TYPE = 0x40006b08; // uint16, read/write : Flash write size select
            public const uint FLASH_PROGRAM_TYPE_SINGLE = 0x0; // State : Program a single 32-bit word, 16-bit word or byte of flash
            public const uint FLASH_PROGRAM_TYPE_ROW = 0x1; // State : Program a flash row (128 bytes)
            public const uint FLASH_PROGRAM_TYPE_SECTOR = 0x2; // State : Program a flash sector (512 bytes)
            public const uint FLASH_PROGRAM_TYPE_SINGLE_BYTE = 0x3; // State : Program a flash byte
            public const uint FLASH_STATUS = 0x40006b0c; // uint16, read/write : Flash status
            public const uint FLASH_STATUS_INTERRUPT = 0x1; // Bitfield : Indicates interrupt has occured. Set to clear.
            public const uint FLASH_STATUS_IDLE = 0x2; // Bitfield : Indicates flash controller idle
            public const uint FLASH_STATUS_ROW_TIMEOUT = 0x4; // Bitfield : Indicates flash programming timed out
        public const uint FLASH_BANK_PROTECT = 0x40006b10; // uint16, read/write : Flash bank protection configuration. Write to flash_unlock then set to enable access.
            public const uint FLASH_BANK_PROTECT_BANK_0_READ = 0x1; // Bitfield : Flash bank 0 (0 - 64K) read protect
            public const uint FLASH_BANK_PROTECT_BANK_1_READ = 0x2; // Bitfield : Flash bank 1 (64K - 96K) read protect
            public const uint FLASH_BANK_PROTECT_BANK_2_READ = 0x4; // Bitfield : Flash bank 2 (96K - 128K) read protect
            public const uint FLASH_BANK_PROTECT_NVR_READ = 0x8; // Bitfield : Flash NVR read protect
            public const uint FLASH_BANK_PROTECT_BANK_0_WRITE = 0x10; // Bitfield : Flash bank 0 (0 - 64K) write protect
            public const uint FLASH_BANK_PROTECT_BANK_1_WRITE = 0x20; // Bitfield : Flash bank 1 (64K - 96K) write protect
            public const uint FLASH_BANK_PROTECT_BANK_2_WRITE = 0x40; // Bitfield : Flash bank 2 (96K - 128K) write protect
            public const uint FLASH_BANK_PROTECT_NVR_WRITE = 0x80; // Bitfield : Flash NVR write protect
        public const uint FLASH_UNLOCK = 0x40006b14; // uint16, read/write : Flash unlock register, write a key here to control an area of flash
        public const uint FLASH_SECTOR_ERASE = 0x40006bd8; // uint16, read/write : Flash sector erase command:0 for disable, 1 for enable
        public const uint FLASH_READ_ADDRESS = 0x40006bdc; // uint32, read/write : Flash read address
        public const uint FLASH_READ_DATA = 0x40006be0; // uint32, read/write : Flash read data port
        public const uint FLASH_WRITE_ADDRESS = 0x40006be4; // uint32, read/write : Flash write address
        public const uint FLASH_WRITE_DATA = 0x40006bec; // uint32, read/write : Flash write data port
        public const uint HIF_RD_ADDR = 0x6d00; // uint32, read/write : Host interface read address
        public const uint HIF_WR_ADDR = 0x6d04; // uint32, read/write : Host interface write address
        public const uint HIF_DATA_LEN = 0x6d08; // uint16, read/write : Host interface data length
        public const uint HIF_DATA_PORT = 0x6d10; // uint32, read/write : Host interface data port
        public const uint HIF_CHECKSUM_ENABLE = 0x6d14; // uint16, read/write : Host interface checksum enable:0 for off, 1 for enable
        public const uint HIF_CHECKSUM = 0x6d18; // uint16, read/write : Host interface checksum value
        public const uint HIF_STATUS = 0x6d1c; // uint16, read-only : Host interface status:0 for idle, 1 for busy
            public const uint HIF_STATUS_DMA_BUSY = 0x1; // Bitfield : HIF Status Direct Memory Access busy flag
            public const uint HIF_STATUS_ERROR = 0x2; // Bitfield : HIF Status error flag


        //
            public const uint DEFAULT_ENABLE_VALUE = 0x1;
            public const uint DEFAULT_DISABLE_VALUE = 0x0;
    }
}
